language: node_js
node_js:
  - "7"
  - "6"
  - "5"
  - "4"
script:
  - npm run check
  - npm test
  - npm run coverage
after_success:
  - npm install -g codecov
  - node_modules/.bin/nyc report --reporter=text-lcov > coverage.lcov && codecov
